services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nalysys
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nalysys
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  database:
  redis: